config/routes.rb
StepperMonitor::Application.routes.draw do
  root to: 'home#index'

  resources :steps
  resources :users

  controller :sessions do
    get 'login'  => :create
    get 'logout' => :destroy
  end

  controller :graphs do
    get 'graphs' => :index
    get 'graphs/:start/:end' => :index
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date, :steps
  default_scope order: 'date ASC'

  validates :date, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :steps
  attr_accessible :name

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
    def user_selected
      unless session[:user_id]
        redirect_to root_path, alert: 'Please select a user first'
      end
    end

    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_filter :user_selected

  def index
    series = Array.new
    series << {
      name: current_user.name,
      data: current_user.steps.collect { |s| [s.date.to_time.to_i*1000, s.steps] }.to_json
    }

    @seriesJS = ''
    series.each { |s| @seriesJS += "{ name: '#{s[:name]}', data: #{s[:data]} }" }

    respond_to do |format|
      format.html # index.html.slim
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find(params[:user_id])

    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome #{user.name}"
    else
      redirect_to root_path, alert: 'Unknown user selected'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :user_selected

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.paginate(page: params[:page], per_page: 15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = current_user.steps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = current_user.steps.new(params[:step])

    p @step.date

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to steps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_sidebar.html.slim
.well.sidebar-nav
  - if session[:user_id]
    h3= current_user.name
    ul.nav.nav-list
      li.nav-header Stats
      li
        | Average : 
        = current_user.steps.average(:steps).to_i
      li
        | Maximum : 
        = current_user.steps.maximum(:steps)
      li
        | Total : 
        = current_user.steps.sum(:steps)

  - else
    h3 Select a user
    ul.nav.nav-pills.nav-stacked
      - User.all.each do |user|
        li= link_to user.name, login_path(user_id: user.id)

app/views/graphs/index.html.slim
#graph

javascript:
  var chart1; // globally available
  $(document).ready(function() {
    chart1 = new Highcharts.Chart({
      chart: {
        renderTo: 'graph',
        zoomType: 'x'
      },
      title: {
        text: 'Step Count'
      },
      xAxis: {
        type: 'datetime',
        maxZoom: 7 * 24 * 60 * 60 * 1000,
        dateTimeLabelFormats: {
          month: '%e. %b',
          year: '%b'
        }
      },
      yAxis: {
          title: {
          text: 'Steps taken'
        }
      },
      series: [#{@seriesJS}]
    });
  });

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    title= content_for?(:title) ? yield(:title) : 'Stepper Monitor'
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag 'http://html5shim.googlecode.com/svn/trunk/html5.js'
    /! Le styles
    = stylesheet_link_tag 'application', :media => 'all'
    /! Le javascript
    = javascript_include_tag 'application'
    / Le fav and touch icons
    link href='images/favicon.ico' rel='shortcut icon'
    link href='images/apple-touch-icon.png' rel='apple-touch-icon'
    link href='images/apple-touch-icon-72x72.png' rel='apple-touch-icon' sizes='72x72'
    link href='images/apple-touch-icon-114x114.png' rel='apple-touch-icon' sizes='114x114'


  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target='.nav-collapse' data-toggle='collapse'
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href='#'Stepper Monitor
          .container.nav-collapse
            ul.nav
              li= link_to 'Home', root_path
              li= link_to 'Steps', steps_path
              li= link_to 'Graphs', graphs_path
            ul.nav.pull-right
              li.dropdown
                a.dropdown-toggle href="#" data-toggle="dropdown"
                  | Users
                  b.caret
                ul.dropdown-menu
                  - User.all.each do |user|
                    li= link_to user.name, login_path(user_id: user.id)
                  li.divider
                  li= link_to 'Manage Users', users_path

    .container

      .content
        .row
          .span9
            - if alert
              .alert.alert-error= alert
            - if notice
              .alert.alert-info= notice
            = yield
          .span3
            = render 'sidebar'
    
      footer
        p &copy; Company 2012

app/views/steps/_form.html.slim
= simple_form_for @step do |f|
  .clearfix
    = f.label :date, t("activerecord.attributes./step.date", :default => "Date"), :class => :label
    .input
      = f.input :date, as: :date_picker
  .clearfix
    = f.label :steps, t("activerecord.attributes./step.steps", :default => "Steps"), :class => :label
    .input
      = f.input :steps

  .form-actions
    button class="btn primary" type="submit" Save
    |  or 
    = link_to "Cancel", steps_path

app/views/steps/edit.html.slim
= render 'form'

app/views/steps/index.html.slim
h1 Steps
table class="table table-striped"
  thead
    tr
      th Date
      th Steps
      th Actions
  tbody
    - @steps.each do |step|
      tr
        td= step.date
        td= step.steps
        td
          = link_to "Show", step_path(step)
          = link_to "Edit", edit_step_path(step)
          = link_to "Destroy", step_path(step), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"

= will_paginate

= link_to "New", new_step_path, :class => 'btn btn-primary'

app/views/steps/new.html.slim
= render 'form'

app/views/steps/show.html.slim
label class="label"= t("activerecord.attributes.step.user_id", :default => t("activerecord.labels.user_id", :default => "User")) + ":"
p= @step.user_id
label class="label"= t("activerecord.attributes.step.date", :default => t("activerecord.labels.date", :default => "Date")) + ":"
p= @step.date
label class="label"= t("activerecord.attributes.step.steps", :default => t("activerecord.labels.steps", :default => "Steps")) + ":"
p= @step.steps

.form-actions
  = link_to "Back", steps_path, :class => 'btn'
  = link_to "Edit", edit_step_path(@step), :class => 'btn'
  = link_to "Delete", step_path(@step), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  .clearfix
    = f.label :name, t("activerecord.attributes./user.name", :default => "Name"), :class => :label
    .input
      = f.input :name, label: false

  .form-actions
    button class="btn primary" type="submit" Save
    |  or 
    = link_to "Cancel", users_path

app/views/users/edit.html.slim
= render 'form'

app/views/users/index.html.slim
h1 Users
table class="table table-striped"
  thead
    tr
      th ID
      th
        = t("activerecord.attributes.user.name", :default => t("activerecord.labels.name", :default => "Name"))
      th Created at
      th Actions
  tbody
    - @users.each do |user|
      tr
        td= user.id
        td= link_to user.name, user_path(user)
        td= user.created_at
        td
          = link_to "Show", user_path(user)
          = link_to "Edit", edit_user_path(user)
          = link_to "Destroy", user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"

= link_to "New", new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
label class="label"= t("activerecord.attributes.user.name", :default => t("activerecord.labels.name", :default => "Name")) + ":"
p= @user.name

.form-actions
  = link_to "Back", users_path, :class => 'btn'
  = link_to "Edit", edit_user_path(@user), :class => 'btn'
  = link_to "Delete", user_path(@user), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'